// <auto-generated />
namespace SQL_Mike_03_19_20.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class testimonials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testimonials));
        
        string IMigrationMetadata.Id
        {
            get { return "201910030935122_testimonials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
